export enum TechnologyEnum {
    Agile = 'Agile',
    Angular = 'Angular',
    Cypress = 'Cypress',
    Directus = 'Directus',
    Express = 'ExpressJs',
    HTML5 = 'HTML5',
    Ionic = 'Ionic',
    Java = 'Java',
    Jasmine = 'Jasmine',
    Jest = 'Jest',
    NestJS = 'NestJs',
    NGRX = 'NgRx',
    Pact = 'Pact',
    RXJS = 'RxJs',
    React = 'ReactJs',
    SASS = 'SASS',
    Typescript = 'Typescript',
    UI = 'UI'
}