export enum KeywordsEnum {
    Code = 'Code',
    Contact = 'Contact',
    CV = 'CV',
    Design = 'Design',
    Development = 'Development',
    Education = 'Education',
    Email = 'Email',
    Employment = 'Employment',
    Experience = 'Experience',
    Github = 'Github',
    Portfolio = 'Portfolio',
    Skills = 'Skills',
    UI = 'UI',
}