export enum LinkEnum {
    Angular = 'https://angular.io',
    Cypress = 'https://www.cypress.io/',
    Directus = 'https://directus.io/',
    Docker = 'https://www.docker.com/',
    Github = 'https://github.com/',
    Gitlab = 'https://about.gitlab.com/',
    HTML5 = 'https://developer.mozilla.org/en-US/docs/Glossary/HTML5',
    Illustrator = 'https://www.adobe.com/uk/products/illustrator.html',
    InDesign = 'https://www.adobe.com/uk/products/indesign.html',
    Inkscape = 'https://inkscape.org/',
    Ionic = 'https://ionicframework.com/',
    Jasmine = 'https://jasmine.github.io/',
    Jest = 'https://jestjs.io/',
    NestJS = 'https://nestjs.com/',
    NGRX = 'https://ngrx.io/',
    Pact = 'https://pact.io/',
    Photoshop = 'https://www.adobe.com/uk/products/photoshop.html',
    Postman = 'https://www.postman.com/',
    RXJS = 'https://rxjs.dev/',
    SASS = 'https://sass-lang.com/',
    Typescript = 'https://www.typescriptlang.org/',
    UI = 'https://www.uxdesigninstitute.com/blog/what-is-ui-design/',
    XD = 'https://www.nobledesktop.com/learn/adobe-xd/what-is-adobe-xd',
    VSCode = 'https://code.visualstudio.com/',

}