export enum LogoEnum {
    Angular = '../../assets/img/angular_logo.svg',
    Cypress = '../../assets/img/cypress_logo.svg',
    RXJS = '../../assets/img/rxjs_logo.svg',
    Typescript = '../../assets/img/typescript_logo.svg',
    SASS = '../../assets/img/sass_logo.svg',
    UI = '../../assets/img/ux_logo.svg',
    NGRX = '../../assets/img/ngrx_logo.svg',
    Illustrator = '../../assets/img/illustrator_logo.svg',
    InDesign = '../../assets/img/indesign_logo.svg',
    Inkscape = '../../assets/img/inkscape_logo.svg',
    Jest = '../../assets/img/jest_logo.svg',
    Jasmine = '../../assets/img/jasmine_logo.svg',
    NestJs = '../../assets/img/nestjs_logo.svg',
    Pact = '../../assets/img/pact_logo.svg',
    Photoshop = '../../assets/img/photoshop_logo.svg',
    Postman = '../../assets/img/postman_logo.svg',
    Agile = '../../assets/img/agile_logo.svg',
    HTML5 = '../../assets/img/html5_logo.svg',
    Ionic = '../../assets/img/ionic_logo.svg',
    Directus = '../../assets/img/directus_logo.svg',
    Java = '../../assets/img/java_logo.svg',
    VSCode = '../../assets/img/vscode_logo.svg',
    XD = '../../assets/img/xd_logo.svg',
}